version: "3"
services:
  my-container:
    image: server
    ports:
      - 8080:3500
    volumes:
      - /home/long1100/temp:/usr/src/app
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - 5672:5672
      - 15672:15672
  