version: "3"
services:
  my-container:
    image: server
    ports:
      - 8080:3500
    volumes:
      - /home/long1100/temp:/usr/src/app
      
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports: 
      - 27017:27017
    volumes:
      - /home/long1100/Database:/data/db
    env_file:
      - .env
